feeStructure.factory('feesAmount',function () {


		var feeData  = {  
		   "Exam Fee":{  
		      "INDIAN":{  
		         "Mental":{  
		            "UG":{  
		               "amount":400
		            },
		            "PG":{  
		               "amount":400
		            },
		            "Diploma":{  
		               "amount":400
		            },
		            "Ph.D":{  
		               "amount":400
		            }
		         },
		         "Dental":{  
		             "UG":{  
		               "amount":400
		            },
		            "PG":{  
		               "amount":400
		            },
		            "Diploma":{  
		               "amount":400
		            },
		            "Ph.D":{  
		               "amount":400
		            }
		         },
		         "Ayurveda":{  
		             "UG":{  
		               "amount":400
		            },
		            "PG":{  
		               "amount":400
		            },
		            "Diploma":{  
		               "amount":400
		            },
		            "Ph.D":{  
		               "amount":400
		            }
		         }
		      },
		      "FOREIGN":{  
		         "Mental":{  
		             "UG":{  
		               "amount":100
		            },
		            "PG":{  
		               "amount":100
		            },
		            "Diploma":{  
		               "amount":100
		            },
		            "Ph.D":{  
		               "amount":100
		            }
		         },
		         "Dental":{  
		            "UG":{  
		              "amount":100
		           },
		           "PG":{  
		              "amount":100
		           },
		           "Diploma":{  
		              "amount":100
		           },
		           "Ph.D":{  
		              "amount":100
		           }
		         },
		         "Ayurveda":{  
		             "UG":{  
		               "amount":100
		            },
		            "PG":{  
		               "amount":100
		            },
		            "Diploma":{  
		               "amount":100
		            },
		            "Ph.D":{  
		               "amount":100
		            }
		         }
		      },
		      "NRI":{  
		         "Mental":{  
		            "UG":{  
		              "amount":600
		           },
		           "PG":{  
		              "amount":600
		           },
		           "Diploma":{  
		              "amount":600
		           },
		           "Ph.D":{  
		              "amount":600
		           }
		         },
		         "Dental":{  
		             "UG":{  
		              "amount":600
		           },
		           "PG":{  
		              "amount":600
		           },
		           "Diploma":{  
		              "amount":600
		           },
		           "Ph.D":{  
		              "amount":600
		           }
		         },
		         "Ayurveda":{  
		             "UG":{  
		              "amount":600
		           },
		           "PG":{  
		              "amount":600
		           },
		           "Diploma":{  
		              "amount":600
		           },
		           "Ph.D":{  
		              "amount":600
		           }
		         }
		      },
		      "SAARC":{  
		         "Mental":{  
		            "UG":{  
		              "amount":600
		           },
		           "PG":{  
		              "amount":600
		           },
		           "Diploma":{  
		              "amount":600
		           },
		           "Ph.D":{  
		              "amount":600
		           }
		         },
		         "Dental":{  
		            "UG":{  
		              "amount":600
		           },
		           "PG":{  
		              "amount":600
		           },
		           "Diploma":{  
		              "amount":600
		           },
		           "Ph.D":{  
		              "amount":600
		           }
		         },
		         "Ayurveda":{  
		            "UG":{  
		              "amount":600
		           },
		           "PG":{  
		              "amount":600
		           },
		           "Diploma":{  
		              "amount":600
		           },
		           "Ph.D":{  
		              "amount":600
		           }
		         }
		      }
		   },
		   "Application Fee":{  
		      "INDIAN":{  
		         "Mental":{  
		            "UG":{  
		               "amount":200
		            },
		            "UG-DIPLOMA":{  
		               "amount":300
		            },
		            "PG":{  
		               "amount":500
		            }
		         },
		         "Dental":{  
		            "UG":{  
		               "amount":200
		            },
		            "UG-DIPLOMA":{  
		               "amount":300
		            },
		            "PG":{  
		               "amount":500
		            }
		         },
		         "Ayurveda":{  
		            "UG":{  
		               "amount":200
		            },
		            "UG-DIPLOMA":{  
		               "amount":300
		            },
		            "PG":{  
		               "amount":500
		            }
		         }
		      },
		      "FOREIGN":{  
		         "Mental":{  
		            "UG":{  
		               "amount":400
		            },
		            "UG-DIPLOMA":{  
		               "amount":400
		            },
		            "PG":{  
		               "amount":700
		            }
		         },
		         "Dental":{  
		            "UG":{  
		               "amount":400
		            },
		            "UG-DIPLOMA":{  
		               "amount":400
		            },
		            "PG":{  
		               "amount":700
		            }
		         },
		         "Ayurveda":{  
		            "UG":{  
		               "amount":400
		            },
		            "UG-DIPLOMA":{  
		               "amount":400
		            },
		            "PG":{  
		               "amount":700
		            }
		         }
		      }
		   }
		}

		return feeData;
	});